// Flat config. ESLint 9 dropped `.eslintrc.json` as the default format and
// ESLint 10 removed the compatibility path entirely, so this file replaces the
// old rc file rather than sitting alongside it.
//
// Two translations were needed and are worth naming, because neither is a
// rename: the old `env` block is now explicit `languageOptions.globals`
// (hence the `globals` package), and `ignorePatterns` is now a config object
// containing only `ignores`, which is what makes it apply globally instead of
// to one block.
import js from "@eslint/js";
import globals from "globals";

export default [
	{
		// Global ignores. `dist/` and `build/` are build output;
		// `build-version.js` and the two manifests are generated by dev/build.js;
		// browser-polyfill is vendored upstream code we do not restyle.
		ignores: [
			"dist/",
			"build/",
			"src/config/build-version.js",
			"src/manifest-chromium.json",
			"src/manifest-firefox.json",
			"src/lib/browser-polyfill.min.js",
		],
	},
	js.configs.recommended,
	{
		files: ["**/*.js"],
		languageOptions: {
			ecmaVersion: "latest",
			sourceType: "module",
			globals: {
				...globals.browser,
				...globals.webextensions,
				browser: "readonly",
				chrome: "readonly",
			},
		},
		rules: {
			semi: ["error", "always"],
			// `caughtErrors` defaulted to "none" through ESLint 8 and flipped to
			// "all" in 9. Restored deliberately: `catch (e) { return null; }` is
			// a normal shape here and flagging ~150 of them buries the handful
			// of unused-variable warnings that do mean something.
			"no-unused-vars": [
				"warn",
				{ argsIgnorePattern: "^_", caughtErrors: "none" },
			],
			"no-console": "off",
			"no-inner-declarations": "off",
			"no-undef": "off",
			"no-unused-labels": ["warn"],
			indent: "off",
			"no-mixed-spaces-and-tabs": "off",
		},
	},
];
