name: Build and Release Extension

on:
  push:
    tags:
      - "v*" # Run when tag matches v*, like v1.1.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Verify version in manifest.json
        run: |
          MANIFEST_VERSION=$(jq -r .version ./FireFox/manifest.json)
          TAG_VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Manifest version: $MANIFEST_VERSION, Tag version: $TAG_VERSION"
          if [ "$MANIFEST_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version in manifest.json ($MANIFEST_VERSION) doesn't match tag version ($TAG_VERSION)"
            exit 1
          fi

      - name: Package extension
        run: |
          cd FireFox
          ZIP_NAME="../RanobeGemini_${{ steps.get_version.outputs.VERSION }}.zip"
          zip -r $ZIP_NAME * -x "*.git*"
          echo "Created $ZIP_NAME"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./RanobeGemini_${{ steps.get_version.outputs.VERSION }}.zip
          name: Ranobe Gemini v${{ steps.get_version.outputs.VERSION }}
          body: |
            Ranobe Gemini Firefox Extension v${{ steps.get_version.outputs.VERSION }}

            Changes in this version:
            - Please check the CHANGELOG.md file for detailed changes
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
